baseURL: 'https://mingbocui.github.io/'
languageCode: 'en-us'
title: 'Cheap Talk'
paginate: 6
theme: "PaperMod"


params:
    defaultTheme: auto
    ShowShareButtons: true
    ShowReadingTime: true
    ShowCodeCopyButtons: true
    ShowBreadCrumbs: true
    ShowToc: true
    comments: false
    mathjax: true

    markup:
      markup.goldmark:
        markup.goldmark.renderer:
          unsafe = true

    homeInfoParams:
        Title: Hi! 👋
        Content: Hello! I'm an NLP/ML engineer based in Zürich. This blog documents my learning journey. 

    socialIcons:
        - name: github
          url: "https://github.com/mingbocui"
        - name: LinkedIn
          url: "https://www.linkedin.com/in/mingbocui/"
        # - name: KoFi
        #   url: "https://ko-fi.com/mingbocui"
        # - name: PayPal
        #   url: "https://www.paypal.com/paypalme/MingboCui"  

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 10
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
